name: Web Component CI/CD

on:
  push:
    branches:
      - main
    tags:
      - v*
env:
  CDN_BUCKET: gs://test_cdn_starter

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # https://github.com/marketplace/actions/extract-version-from-tag
      - name: Extract version from tag
        uses: damienaicheh/extract-version-from-tag-action@v1.0.0

      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: npm i --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Verify contents
        run: ls -la

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy Web component
        run: gsutil rsync -m -d -r dist $CDN_BUCKET/$MAJOR.$MINOR.$PATCH
