name: Web Component CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
 
      - name: Install Dependencies
        run: npm i --legacy-peer-deps
        
      - name: Build
        run: npm run build
        
      - name: Verify contents
        run: ls -la
        
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
#         with:
#           project_id: ${{ secrets.GCP_PROJECT_ID }}
#           service_account_key: ${{ secrets.GCP_SA_KEY }}
#           export_default_credentials: true

      - name: Deploy Web component
        run: gsutil rsync -d -r dist gs://test_cdn_starter

      - name: Invalidate CDN Cache
        run: gcloud compute url-maps invalidate-cdn-cache lb-web --path '/*' --async
