name: Web Component CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
        
      - name: Install Dependencies
        run: npm i
        
      - name: Build
        run: npm run build
        
      - name: Verify contents
        run: ls -la

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
 
      - name: Install Dependencies
        run: npm i
        
      - name: Build
        run: npm run build
        
      - name: Verify contents
        run: ls -la

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy Web component
        run: gsutil rsync -d -r dist gs://test_cdn_starter

      - name: Invalidate CDN Cache
        run: gcloud compute url-maps invalidate-cdn-cache lb-web --path "/*"
